# Manual prediction

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
weight = np.array([2,4,5,3,6,5,7])
price = np.array([35,60,20,50,50,55,60])

In [5]:
df = pd.DataFrame({'weight':weight,'price':price})
df

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

In [8]:
mean_weight=np.mean(weight)
mean_price = np.mean(price)
slope_m = np.sum((weight-mean_weight)*(price-mean_price))/np.sum((weight-mean_weight)**2)
intercept_c = mean_price-slope_m*mean_weight

In [9]:
prediction = slope_m * 6 + intercept_c
prediction

50.88709677419355

# calculate residual by using Sklearn

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg = LinearRegression()

In [13]:
reg.fit(df[['weight']],df[['price']])

LinearRegression()

In [14]:
reg.coef_

array([[2.62096774]])

In [15]:
reg.intercept_

array([35.16129032])

In [17]:
reg.predict([[6]])

C:\Users\dipda\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[50.88709677]])

In [23]:
pred = reg.predict(df[['weight']])
pred

array([[40.40322581],
       [45.64516129],
       [48.26612903],
       [43.02419355],
       [50.88709677],
       [48.26612903],
       [53.50806452]])

In [22]:
df['predicted weight'] = reg.predict(df[['weight']])
df.head()

weight  price  predicted weight
0       2     35         40.403226
1       4     60         45.645161
2       5     20         48.266129
3       3     50         43.024194
4       6     50         50.887097

# MSE & MAE

In [27]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [28]:
mse = mean_squared_error(df['weight'],df['predicted weight'])
mse

1818.9758064516132

In [29]:
mae = mean_absolute_error(df['weight'],df['predicted weight'])
mae

42.57142857142857

# dataSet to excel 

In [37]:
df1 = pd.DataFrame({'weight': {0: 2, 1: 4, 2: 5,
                                  3: 3, 4: 6, 5: 5,
                                  6: 7},
                   'price': {0: 35, 1: 60, 2: 20,
                                  3: 50, 4: 50, 5: 55,
                                  6: 60}})
df1

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

In [40]:
file_name = 'excel file of data.xlsx'

In [41]:
df1.to_excel(file_name)

In [42]:
df.to_excel('excel file.xlsx')